### ISSUE TITLE
Holding Cloudinary gem back breaks "enhance_image_tag" support (Rails 5 compatibility issue)

### ISSUE THREAD

**Issue by zachallaun** [janko-m/shrine-cloudinary#2]
It appears that the version of `cloudinary` that `shrine-cloudinary` relies on (1.6.0) does not support Rails 5 correctly; in particular, the `enhance_image_tag` configuration option breaks due to the use of a deprecated method.

I saw in the commit history that `cloudinary` is being held back due to [this issue](https://github.com/cloudinary/cloudinary_gem/pull/260). Is it possible that it's either been resolved in newer versions of `cloudinary`, or is it possible for the issue to be addressed somehow with changes to `shine-cloudinary`?

Thanks for your help & work with Shrine.

**Comment by janko-m** [comment]
@zachallaun Yes, it's possible possible to add a hack to shrine-cloudinary which will work around this issue, which definitely seems to be the reasonable path considering that `cloudinary` hasn't been updated for a year.

I'll see if I can make a patch later today.

**Comment by zachallaun** [comment]
Thanks so much for your help @janko-m. Hopefully Cloudinary pulls themselves together at some point, but in the meantime I appreciate you trying to work around the issue.
